spring:
  application:
    name: auth-service
  profiles:
    active: dev
server:
  port: 8081
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
jwt:
  expiration:
    access: PT15M
    refresh: P7D
app:
  base-url: http://localhost:8081
